package main;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Home;

import javax.persistence.EntityManager;
import javax.servlet.ServletContext;

import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.SQLException;


public class AddHouse {

	public void RegisterHouse(EntityManager em, String name, String city, String desc, String subDesc, String type, int guests, 
			String photo, BigDecimal price, String iDate, String fDate) {

		Home home = new Home();
		
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
		Date parsedIDate = new Date(1970, 01, 01);
		Date parsedFDate = new Date(1970, 01, 01);
		try {
			parsedIDate = format.parse(iDate);
			parsedFDate = format.parse(fDate);
		} catch (ParseException e) {
		}
		
		// House id automatically generated by MySQL
		home.setHomeName(name);
		home.setHomeCity(city);
		home.setHomeDescriptionFull(desc);
		home.setHomeDescriptionShort(subDesc);
		home.setHomeType(type);
		home.setHomeGuests(guests);
		home.setHomePhotos(photo);
		home.setHomePriceNight(price);
		home.setHomeAvDateInit(parsedIDate);
		home.setHomeAvDateFin(parsedFDate);

		em.persist(home);


	}

}
